# configs/base_config.yaml

# --- General experiment settings ---
exp_name: "PPC_Ru_attentionpool"
output_dir: "./experiments"  # Main directory to save logs, checkpoints, etc.

# --- Data settings ---
data:
  train_list: "contra_data_clean_noipad/fine_train_Ru copy.txt"
  val_list: "contra_data_clean_noipad/fine_test_Ru copy.txt"
  data_dir: "contra_data_clean_noipad/data_view1"
  num_events: 64
  num_workers: 4 # Number of threads for data loading
  # A list of class names for confusion matrix labels
  class_names: ["1","2","3","4"] #["w/o","beta2","NS+beata2","beta2+beta3","NS+beta3"] 

# --- Model settings (passed to create_model) ---
model:
  model_name: 'PPC'
  input_feature_dim: 3
  output_dim: 512
  num_classes: 5
  feature_out: false
  pretrained_path: null #"/home/qiuyu/SPT/experiments/PPC_Ru_test1_20250806-220852/ckpt_latest.pth" #null
# --- Training settings ---
train:
  batch_size: 16
  max_epochs: 100
  # Optimizer
  optimizer:
    type: "AdamW"
    lr: 0.001
    weight_decay: 0.1
  # Learning rate scheduler
  scheduler:
    type: "CosineAnnealingLR"
    T_max: 100 # Should match max_epochs
  # Checkpointing and validation
  resume_path: null # Set to a .pth file to resume, e.g., "./experiments/PPC_RuZr.../ckpt_latest.pth"
  val_every_n_epochs: 10
  save_every_n_epochs: 20
validation:
  # 在每次验证时，对验证集进行多次重新洗牌和评估，以获得更稳定的结果
  # 设为 1 则与之前行为相同
  num_runs: 5